export const cities = [
  {
    id: 1,
    name: 'Berlin',
    rating: 8.2,
    date: 'Wed 25 Jan-Fri 27 Jan',
    image: 'Berlin.jpeg',
    like: false,
    title:
      'A tour of the city and its surroundings led by a professional guide',
    hotels: [
      {
        id: 1,
        name: 'Leonardo Hotel',
        location: '11 Grunerstrabe, Mitte, 10179 Berlin, Germany',
        description:
          'Situated conveniently in the centre of Berlin, Motel One Berlin-Alexanderplatz offers free WiFi throughout the property and a bar.',
        rating: 7.5,
        price: 4523.74,
        countReviews: 17.872,
        image: 'Berlin.jpeg',
      },
      {
        id: 2,
        name: 'Leonardo Hotel',
        location: '',
        description: '',
        rating: 7.5,
        price: 4523.74,
        countReviews: 17.872,
        image: '',
      },
      {
        id: 3,
        name: 'Leonardo Hotel',
        location: '',
        description: '',
        rating: 7.5,
        price: 4523.74,
        countReviews: 17.872,
        image: '',
      },
    ],
  },
  {
    id: 2,
    name: 'Paris',
    rating: 8.2,
    date: 'Wed 25 Jan-Fri 27 Jan',
    image: 'Paris.jpeg',
    like: false,
    title:
      'A tour of the city and its surroundings led by a professional guide',
    hotels: [
      {
        id: 1,
        name: 'Leonardo Hotel',
        location: '',
        description: '',
        rating: 7.5,
        price: 4523.74,
        countReviews: 17.872,
        image: '',
      },
      {
        id: 2,
        name: 'Leonardo Hotel',
        location: '',
        description: '',
        rating: 7.5,
        price: 4523.74,
        countReviews: 17.872,
        image: '',
      },
      {
        id: 3,
        name: 'Leonardo Hotel',
        location: '',
        description: '',
        rating: 7.5,
        price: 4523.74,
        countReviews: 17.872,
        image: '',
      },
    ],
  },
  {
    id: 3,
    name: 'Madrid',
    rating: 8.2,
    date: 'Wed 25 Jan-Fri 27 Jan',
    image: 'Madrid.jpeg',
    like: false,
    title:
      'A tour of the city and its surroundings led by a professional guide',
    hotels: [
      {
        id: 1,
        name: 'Leonardo Hotel',
        location: '',
        description: '',
        rating: 7.5,
        price: 4523.74,
        countReviews: 17.872,
        image: '',
      },
      {
        id: 2,
        name: 'Leonardo Hotel',
        location: '',
        description: '',
        rating: 7.5,
        price: 4523.74,
        countReviews: 17.872,
        image: '',
      },
      {
        id: 3,
        name: 'Leonardo Hotel',
        location: '',
        description: '',
        rating: 7.5,
        price: 4523.74,
        countReviews: 17.872,
        image: '',
      },
    ],
  },
  {
    id: 4,
    name: 'Madrid',
    rating: 8.2,
    date: 'Wed 25 Jan-Fri 27 Jan',
    image: 'Madrid.jpeg',
    like: false,
    title:
      'A tour of the city and its surroundings led by a professional guide',
    hotels: [
      {
        id: 1,
        name: 'Leonardo Hotel',
        location: '',
        description: '',
        rating: 7.5,
        price: 4523.74,
        countReviews: 17.872,
        image: '',
      },
      {
        id: 2,
        name: 'Leonardo Hotel',
        location: '',
        description: '',
        rating: 7.5,
        price: 4523.74,
        countReviews: 17.872,
        image: '',
      },
      {
        id: 3,
        name: 'Leonardo Hotel',
        location: '',
        description: '',
        rating: 7.5,
        price: 4523.74,
        countReviews: 17.872,
        image: '',
      },
    ],
  },
  {
    id: 5,
    name: 'Madrid',
    rating: 8.2,
    date: 'Wed 25 Jan-Fri 27 Jan',
    image: 'Madrid.jpeg',
    like: false,
    title:
      'A tour of the city and its surroundings led by a professional guide',
    hotels: [
      {
        id: 1,
        name: 'Leonardo Hotel',
        location: '',
        description: '',
        rating: 7.5,
        price: 4523.74,
        countReviews: 17.872,
        image: '',
      },
      {
        id: 2,
        name: 'Leonardo Hotel',
        location: '',
        description: '',
        rating: 7.5,
        price: 4523.74,
        countReviews: 17.872,
        image: '',
      },
      {
        id: 3,
        name: 'Leonardo Hotel',
        location: '',
        description: '',
        rating: 7.5,
        price: 4523.74,
        countReviews: 17.872,
        image: '',
      },
    ],
  },
];
